### PR TITLE
Various fixes for pangzero

### PR DESCRIPTION
**Pull request by jwrdegoede**
Hi,

Short intro I'm the Fedora packager of pangzero, and since Fedora has moved to the latest perl-sdl, I've been working on upgrading my packages to your git version of pangzero. During testing I've found and fixed quite a few issues, see the patches in this git pull request.

Known remaining issues:
- The machinegun is borken (disabled for now)
- All the options under the help menu are broken
- Select to run in windowed mode, exit, restart, still fullscreen

Thanks & Regards,

Hans

### CODE REVIEW

**Comment by kthakore** [comment]
Thank you! I will update this ASAP!

Kartik Thakore

On 2012-10-29, at 4:57 PM, Hans de Goede notifications@github.com wrote:

Hi,

Short intro I'm the Fedora packager of pangzero, and since Fedora has moved
to the latest perl-sdl, I've been working on upgrading my packages to your
git version of pangzero. During testing I've found and fixed quite a few
issues, see the patches in this git pull request.

Known remaining issues:
- The machinegun is borken (disabled for now)
- All the options under the help menu are broken
- Select to run in windowed mode, exit, restart, still fullscreen

Thanks & Regards,

## Hans

You can merge this Pull Request by running:

  git pull https://github.com/jwrdegoede/pangzero master

Or view, comment on, or merge it at:

  https://github.com/kthakore/pangzero/pull/2
Commit Summary
- Fix pang-zero hanging on exit when showing website and no browser is …
- Don't try to show a dialog while in full-screen mode
- Fix disabling of ShowWebsite not working with x.y.z numbers
- s/Games::PangZero::PlaySound/Games::PangZero::Music::PlaySound/
- Fix Challenge Game not working
- Fix entering a new highscore not working
- Fix crash when getting the xmass-ball
- Disable the MachineGun
- Fix powerwire not working
- Replace SDL::Color->new() calls with SDL::Video::map_RGB
- Properly clear score area before redrawing

File Changes
- _M_ lib/Games/PangZero.pm (39)
- _M_ lib/Games/PangZero/BonusDrop.pm (3)
- _M_ lib/Games/PangZero/ChallengeGame.pm (24)
- _M_ lib/Games/PangZero/Config.pm (5)
- _M_ lib/Games/PangZero/DemoPlaybackGame.pm (2)
- _M_ lib/Games/PangZero/GameObject.pm (2)
- _M_ lib/Games/PangZero/Graphics.pm (2)
- _M_ lib/Games/PangZero/Guy.pm (2)
- _M_ lib/Games/PangZero/Highscore.pm (15)
- _M_ lib/Games/PangZero/MachineGun.pm (2)
- _M_ lib/Games/PangZero/Menu.pm (6)
- _M_ lib/Games/PangZero/MenuItem.pm (2)
- _M_ lib/Games/PangZero/PanicGame.pm (2)
- _M_ lib/Games/PangZero/PlayableGameBase.pm (4)
- _M_ lib/Games/PangZero/PowerWire.pm (4)
- _M_ lib/Games/PangZero/XmasBall.pm (6)

Patch Links
- https://github.com/kthakore/pangzero/pull/2.patch
- https://github.com/kthakore/pangzero/pull/2.diff
  
  —
  Reply to this email directly or view it on
  GitHubhttps://github.com/kthakore/pangzero/pull/2.

**Comment by jwrdegoede** [comment]
Hi,

Me again :)  I've done some more work on pangzero fixing all remaining issues I'm aware of!

Regards,

Hans

**Comment by kthakore** [comment]
Awesome.

Can you run perl Build test? And check if that is working?

**Comment by jwrdegoede** [comment]
Hi,

That seems to work fine too:

[hans@shalem pangzero]$ perl Build test
t/00-run.t .. ok
All tests successful.
Files=1, Tests=1, 53 wallclock secs ( 0.02 usr  0.00 sys +  2.70 cusr  0.13 csys =  2.85 CPU)
Result: PASS

Regards,

Hans

**Comment by kthakore** [comment]
Awesome pulling now.

**Pull request merged**
